/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PikiOptions,
  PikiOptionsPatch,
} from '../models/index';
import {
    PikiOptionsFromJSON,
    PikiOptionsToJSON,
    PikiOptionsPatchFromJSON,
    PikiOptionsPatchToJSON,
} from '../models/index';

export interface CoreApiUpdateOptionsRequest {
    pikiOptionsPatch: PikiOptionsPatch;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Return current tuning values so the frontend can initialise its controls.
     * Get Options
     */
    async coreApiGetOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PikiOptions>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/options`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PikiOptionsFromJSON(jsonValue));
    }

    /**
     * Return current tuning values so the frontend can initialise its controls.
     * Get Options
     */
    async coreApiGetOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PikiOptions> {
        const response = await this.coreApiGetOptionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Discard the MOG2 background model so it relearns the current scene.
     * Reset Background
     */
    async coreApiResetBackgroundRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/reset_background`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Discard the MOG2 background model so it relearns the current scene.
     * Reset Background
     */
    async coreApiResetBackground(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiResetBackgroundRaw(initOverrides);
    }

    /**
     * Update Options
     */
    async coreApiUpdateOptionsRaw(requestParameters: CoreApiUpdateOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PikiOptions>> {
        if (requestParameters['pikiOptionsPatch'] == null) {
            throw new runtime.RequiredError(
                'pikiOptionsPatch',
                'Required parameter "pikiOptionsPatch" was null or undefined when calling coreApiUpdateOptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/update_options`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PikiOptionsPatchToJSON(requestParameters['pikiOptionsPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PikiOptionsFromJSON(jsonValue));
    }

    /**
     * Update Options
     */
    async coreApiUpdateOptions(requestParameters: CoreApiUpdateOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PikiOptions> {
        const response = await this.coreApiUpdateOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Video streaming route.
     * Video Feed
     */
    async coreApiVideoFeedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/video_feed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Video streaming route.
     * Video Feed
     */
    async coreApiVideoFeed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.coreApiVideoFeedRaw(initOverrides);
        return await response.value();
    }

}
