/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AimConfigSchema,
  AimConfigSchemaPatch,
  PikiOptions,
  PikiOptionsPatch,
  ServoMoveSchema,
  ServoPositionSchema,
} from '../models/index';
import {
    AimConfigSchemaFromJSON,
    AimConfigSchemaToJSON,
    AimConfigSchemaPatchFromJSON,
    AimConfigSchemaPatchToJSON,
    PikiOptionsFromJSON,
    PikiOptionsToJSON,
    PikiOptionsPatchFromJSON,
    PikiOptionsPatchToJSON,
    ServoMoveSchemaFromJSON,
    ServoMoveSchemaToJSON,
    ServoPositionSchemaFromJSON,
    ServoPositionSchemaToJSON,
} from '../models/index';

export interface CoreApiServoMoveRequest {
    servoMoveSchema: ServoMoveSchema;
}

export interface CoreApiUpdateAimConfigRequest {
    aimConfigSchemaPatch: AimConfigSchemaPatch;
}

export interface CoreApiUpdateOptionsRequest {
    pikiOptionsPatch: PikiOptionsPatch;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Return current servo aim configuration.
     * Get Aim Config
     */
    async coreApiGetAimConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AimConfigSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/aim_config`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AimConfigSchemaFromJSON(jsonValue));
    }

    /**
     * Return current servo aim configuration.
     * Get Aim Config
     */
    async coreApiGetAimConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AimConfigSchema> {
        const response = await this.coreApiGetAimConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Return current tuning values so the frontend can initialise its controls.
     * Get Options
     */
    async coreApiGetOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PikiOptions>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/options`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PikiOptionsFromJSON(jsonValue));
    }

    /**
     * Return current tuning values so the frontend can initialise its controls.
     * Get Options
     */
    async coreApiGetOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PikiOptions> {
        const response = await this.coreApiGetOptionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Return the list of all detectable YOLO class names.
     * Get Yolo Classes
     */
    async coreApiGetYoloClassesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/yolo_classes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Return the list of all detectable YOLO class names.
     * Get Yolo Classes
     */
    async coreApiGetYoloClasses(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.coreApiGetYoloClassesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Discard the MOG2 background model so it relearns the current scene.
     * Reset Background
     */
    async coreApiResetBackgroundRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/reset_background`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Discard the MOG2 background model so it relearns the current scene.
     * Reset Background
     */
    async coreApiResetBackground(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiResetBackgroundRaw(initOverrides);
    }

    /**
     * Manually command both servos to explicit angles (debug / calibration mode).
     * Servo Move
     */
    async coreApiServoMoveRaw(requestParameters: CoreApiServoMoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServoPositionSchema>> {
        if (requestParameters['servoMoveSchema'] == null) {
            throw new runtime.RequiredError(
                'servoMoveSchema',
                'Required parameter "servoMoveSchema" was null or undefined when calling coreApiServoMove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/servo/move`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServoMoveSchemaToJSON(requestParameters['servoMoveSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServoPositionSchemaFromJSON(jsonValue));
    }

    /**
     * Manually command both servos to explicit angles (debug / calibration mode).
     * Servo Move
     */
    async coreApiServoMove(requestParameters: CoreApiServoMoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServoPositionSchema> {
        const response = await this.coreApiServoMoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update servo aim configuration and persist to database.
     * Update Aim Config
     */
    async coreApiUpdateAimConfigRaw(requestParameters: CoreApiUpdateAimConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AimConfigSchema>> {
        if (requestParameters['aimConfigSchemaPatch'] == null) {
            throw new runtime.RequiredError(
                'aimConfigSchemaPatch',
                'Required parameter "aimConfigSchemaPatch" was null or undefined when calling coreApiUpdateAimConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/aim_config`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AimConfigSchemaPatchToJSON(requestParameters['aimConfigSchemaPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AimConfigSchemaFromJSON(jsonValue));
    }

    /**
     * Update servo aim configuration and persist to database.
     * Update Aim Config
     */
    async coreApiUpdateAimConfig(requestParameters: CoreApiUpdateAimConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AimConfigSchema> {
        const response = await this.coreApiUpdateAimConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Options
     */
    async coreApiUpdateOptionsRaw(requestParameters: CoreApiUpdateOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PikiOptions>> {
        if (requestParameters['pikiOptionsPatch'] == null) {
            throw new runtime.RequiredError(
                'pikiOptionsPatch',
                'Required parameter "pikiOptionsPatch" was null or undefined when calling coreApiUpdateOptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/update_options`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PikiOptionsPatchToJSON(requestParameters['pikiOptionsPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PikiOptionsFromJSON(jsonValue));
    }

    /**
     * Update Options
     */
    async coreApiUpdateOptions(requestParameters: CoreApiUpdateOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PikiOptions> {
        const response = await this.coreApiUpdateOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Video streaming route.
     * Video Feed
     */
    async coreApiVideoFeedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/video_feed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Video streaming route.
     * Video Feed
     */
    async coreApiVideoFeed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.coreApiVideoFeedRaw(initOverrides);
        return await response.value();
    }

}
