[project]
name = "pi-ki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ai-edge-litert==1.4.0",
    "django==5.2.4",
    "flask==3.1.1",
    "gpiozero==2.0.1",
    "numpy==2.3.2",
    "opencv-python-headless==4.11.0.86",
    "picamera2==0.3.30",
    "pigpio==1.78",
    "pillow==11.3.0",
]

[dependency-groups]
dev = [
    "ruff==0.12.7",
]
