/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AimConfigSchema
 */
export interface AimConfigSchema {
    /**
     * 
     * @type {Array<string>}
     * @memberof AimConfigSchema
     */
    targetClasses: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchema
     */
    servoEnabled: boolean;
}

/**
 * Check if a given object implements the AimConfigSchema interface.
 */
export function instanceOfAimConfigSchema(value: object): value is AimConfigSchema {
    if (!('targetClasses' in value) || value['targetClasses'] === undefined) return false;
    if (!('servoEnabled' in value) || value['servoEnabled'] === undefined) return false;
    return true;
}

export function AimConfigSchemaFromJSON(json: any): AimConfigSchema {
    return AimConfigSchemaFromJSONTyped(json, false);
}

export function AimConfigSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AimConfigSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'targetClasses': json['target_classes'],
        'servoEnabled': json['servo_enabled'],
    };
}

export function AimConfigSchemaToJSON(json: any): AimConfigSchema {
    return AimConfigSchemaToJSONTyped(json, false);
}

export function AimConfigSchemaToJSONTyped(value?: AimConfigSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_classes': value['targetClasses'],
        'servo_enabled': value['servoEnabled'],
    };
}

