/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AimConfigSchemaPatch
 */
export interface AimConfigSchemaPatch {
    /**
     * 
     * @type {Array<string>}
     * @memberof AimConfigSchemaPatch
     */
    target_classes?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    servo_enabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchemaPatch
     */
    target_lock_duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchemaPatch
     */
    vertical_angle_offset?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    pan_invert?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    tilt_invert?: boolean | null;
}

/**
 * Check if a given object implements the AimConfigSchemaPatch interface.
 */
export function instanceOfAimConfigSchemaPatch(value: object): value is AimConfigSchemaPatch {
    return true;
}

export function AimConfigSchemaPatchFromJSON(json: any): AimConfigSchemaPatch {
    return AimConfigSchemaPatchFromJSONTyped(json, false);
}

export function AimConfigSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): AimConfigSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'target_classes': json['target_classes'] == null ? undefined : json['target_classes'],
        'servo_enabled': json['servo_enabled'] == null ? undefined : json['servo_enabled'],
        'target_lock_duration': json['target_lock_duration'] == null ? undefined : json['target_lock_duration'],
        'vertical_angle_offset': json['vertical_angle_offset'] == null ? undefined : json['vertical_angle_offset'],
        'pan_invert': json['pan_invert'] == null ? undefined : json['pan_invert'],
        'tilt_invert': json['tilt_invert'] == null ? undefined : json['tilt_invert'],
    };
}

export function AimConfigSchemaPatchToJSON(json: any): AimConfigSchemaPatch {
    return AimConfigSchemaPatchToJSONTyped(json, false);
}

export function AimConfigSchemaPatchToJSONTyped(value?: AimConfigSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_classes': value['target_classes'],
        'servo_enabled': value['servo_enabled'],
        'target_lock_duration': value['target_lock_duration'],
        'vertical_angle_offset': value['vertical_angle_offset'],
        'pan_invert': value['pan_invert'],
        'tilt_invert': value['tilt_invert'],
    };
}

