/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AimConfigSchema
 */
export interface AimConfigSchema {
    /**
     * 
     * @type {Array<string>}
     * @memberof AimConfigSchema
     */
    target_classes: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchema
     */
    servo_enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchema
     */
    target_lock_duration: number;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchema
     */
    vertical_angle_offset?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchema
     */
    pan_invert?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchema
     */
    tilt_invert?: boolean;
}

/**
 * Check if a given object implements the AimConfigSchema interface.
 */
export function instanceOfAimConfigSchema(value: object): value is AimConfigSchema {
    if (!('target_classes' in value) || value['target_classes'] === undefined) return false;
    if (!('servo_enabled' in value) || value['servo_enabled'] === undefined) return false;
    if (!('target_lock_duration' in value) || value['target_lock_duration'] === undefined) return false;
    return true;
}

export function AimConfigSchemaFromJSON(json: any): AimConfigSchema {
    return AimConfigSchemaFromJSONTyped(json, false);
}

export function AimConfigSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AimConfigSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'target_classes': json['target_classes'],
        'servo_enabled': json['servo_enabled'],
        'target_lock_duration': json['target_lock_duration'],
        'vertical_angle_offset': json['vertical_angle_offset'] == null ? undefined : json['vertical_angle_offset'],
        'pan_invert': json['pan_invert'] == null ? undefined : json['pan_invert'],
        'tilt_invert': json['tilt_invert'] == null ? undefined : json['tilt_invert'],
    };
}

export function AimConfigSchemaToJSON(json: any): AimConfigSchema {
    return AimConfigSchemaToJSONTyped(json, false);
}

export function AimConfigSchemaToJSONTyped(value?: AimConfigSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_classes': value['target_classes'],
        'servo_enabled': value['servo_enabled'],
        'target_lock_duration': value['target_lock_duration'],
        'vertical_angle_offset': value['vertical_angle_offset'],
        'pan_invert': value['pan_invert'],
        'tilt_invert': value['tilt_invert'],
    };
}

