/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AimConfigSchemaPatch
 */
export interface AimConfigSchemaPatch {
    /**
     * 
     * @type {Array<string>}
     * @memberof AimConfigSchemaPatch
     */
    targetClasses?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    servoEnabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchemaPatch
     */
    targetLockDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchemaPatch
     */
    aimConfidence?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AimConfigSchemaPatch
     */
    verticalAngleOffset?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    panInvert?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AimConfigSchemaPatch
     */
    tiltInvert?: boolean | null;
}

/**
 * Check if a given object implements the AimConfigSchemaPatch interface.
 */
export function instanceOfAimConfigSchemaPatch(value: object): value is AimConfigSchemaPatch {
    return true;
}

export function AimConfigSchemaPatchFromJSON(json: any): AimConfigSchemaPatch {
    return AimConfigSchemaPatchFromJSONTyped(json, false);
}

export function AimConfigSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): AimConfigSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'targetClasses': json['target_classes'] == null ? undefined : json['target_classes'],
        'servoEnabled': json['servo_enabled'] == null ? undefined : json['servo_enabled'],
        'targetLockDuration': json['target_lock_duration'] == null ? undefined : json['target_lock_duration'],
        'aimConfidence': json['aim_confidence'] == null ? undefined : json['aim_confidence'],
        'verticalAngleOffset': json['vertical_angle_offset'] == null ? undefined : json['vertical_angle_offset'],
        'panInvert': json['pan_invert'] == null ? undefined : json['pan_invert'],
        'tiltInvert': json['tilt_invert'] == null ? undefined : json['tilt_invert'],
    };
}

export function AimConfigSchemaPatchToJSON(json: any): AimConfigSchemaPatch {
    return AimConfigSchemaPatchToJSONTyped(json, false);
}

export function AimConfigSchemaPatchToJSONTyped(value?: AimConfigSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_classes': value['targetClasses'],
        'servo_enabled': value['servoEnabled'],
        'target_lock_duration': value['targetLockDuration'],
        'aim_confidence': value['aimConfidence'],
        'vertical_angle_offset': value['verticalAngleOffset'],
        'pan_invert': value['panInvert'],
        'tilt_invert': value['tiltInvert'],
    };
}

