/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BpuMetrics
 */
export interface BpuMetrics {
    /**
     * 
     * @type {number}
     * @memberof BpuMetrics
     */
    loadPercent: number | null;
    /**
     * 
     * @type {number}
     * @memberof BpuMetrics
     */
    freqMhz: number | null;
}

/**
 * Check if a given object implements the BpuMetrics interface.
 */
export function instanceOfBpuMetrics(value: object): value is BpuMetrics {
    if (!('loadPercent' in value) || value['loadPercent'] === undefined) return false;
    if (!('freqMhz' in value) || value['freqMhz'] === undefined) return false;
    return true;
}

export function BpuMetricsFromJSON(json: any): BpuMetrics {
    return BpuMetricsFromJSONTyped(json, false);
}

export function BpuMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpuMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'loadPercent': json['load_percent'],
        'freqMhz': json['freq_mhz'],
    };
}

export function BpuMetricsToJSON(json: any): BpuMetrics {
    return BpuMetricsToJSONTyped(json, false);
}

export function BpuMetricsToJSONTyped(value?: BpuMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'load_percent': value['loadPercent'],
        'freq_mhz': value['freqMhz'],
    };
}

