/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoolingDevice
 */
export interface CoolingDevice {
    /**
     * 
     * @type {number}
     * @memberof CoolingDevice
     */
    curState: number;
    /**
     * 
     * @type {number}
     * @memberof CoolingDevice
     */
    maxState: number;
}

/**
 * Check if a given object implements the CoolingDevice interface.
 */
export function instanceOfCoolingDevice(value: object): value is CoolingDevice {
    if (!('curState' in value) || value['curState'] === undefined) return false;
    if (!('maxState' in value) || value['maxState'] === undefined) return false;
    return true;
}

export function CoolingDeviceFromJSON(json: any): CoolingDevice {
    return CoolingDeviceFromJSONTyped(json, false);
}

export function CoolingDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoolingDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'curState': json['cur_state'],
        'maxState': json['max_state'],
    };
}

export function CoolingDeviceToJSON(json: any): CoolingDevice {
    return CoolingDeviceToJSONTyped(json, false);
}

export function CoolingDeviceToJSONTyped(value?: CoolingDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cur_state': value['curState'],
        'max_state': value['maxState'],
    };
}

