/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CpuMetrics
 */
export interface CpuMetrics {
    /**
     * 
     * @type {number}
     * @memberof CpuMetrics
     */
    percentTotal: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CpuMetrics
     */
    percentPerCore: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CpuMetrics
     */
    freqMhzPerCore: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CpuMetrics
     */
    freqMinMhz: number;
    /**
     * 
     * @type {number}
     * @memberof CpuMetrics
     */
    freqMaxMhz: number;
    /**
     * 
     * @type {string}
     * @memberof CpuMetrics
     */
    governor: string | null;
    /**
     * 
     * @type {number}
     * @memberof CpuMetrics
     */
    coreCount: number;
}

/**
 * Check if a given object implements the CpuMetrics interface.
 */
export function instanceOfCpuMetrics(value: object): value is CpuMetrics {
    if (!('percentTotal' in value) || value['percentTotal'] === undefined) return false;
    if (!('percentPerCore' in value) || value['percentPerCore'] === undefined) return false;
    if (!('freqMhzPerCore' in value) || value['freqMhzPerCore'] === undefined) return false;
    if (!('freqMinMhz' in value) || value['freqMinMhz'] === undefined) return false;
    if (!('freqMaxMhz' in value) || value['freqMaxMhz'] === undefined) return false;
    if (!('governor' in value) || value['governor'] === undefined) return false;
    if (!('coreCount' in value) || value['coreCount'] === undefined) return false;
    return true;
}

export function CpuMetricsFromJSON(json: any): CpuMetrics {
    return CpuMetricsFromJSONTyped(json, false);
}

export function CpuMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CpuMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'percentTotal': json['percent_total'],
        'percentPerCore': json['percent_per_core'],
        'freqMhzPerCore': json['freq_mhz_per_core'],
        'freqMinMhz': json['freq_min_mhz'],
        'freqMaxMhz': json['freq_max_mhz'],
        'governor': json['governor'],
        'coreCount': json['core_count'],
    };
}

export function CpuMetricsToJSON(json: any): CpuMetrics {
    return CpuMetricsToJSONTyped(json, false);
}

export function CpuMetricsToJSONTyped(value?: CpuMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent_total': value['percentTotal'],
        'percent_per_core': value['percentPerCore'],
        'freq_mhz_per_core': value['freqMhzPerCore'],
        'freq_min_mhz': value['freqMinMhz'],
        'freq_max_mhz': value['freqMaxMhz'],
        'governor': value['governor'],
        'core_count': value['coreCount'],
    };
}

