/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DdrMetrics
 */
export interface DdrMetrics {
    /**
     * 
     * @type {number}
     * @memberof DdrMetrics
     */
    freqMhz: number | null;
}

/**
 * Check if a given object implements the DdrMetrics interface.
 */
export function instanceOfDdrMetrics(value: object): value is DdrMetrics {
    if (!('freqMhz' in value) || value['freqMhz'] === undefined) return false;
    return true;
}

export function DdrMetricsFromJSON(json: any): DdrMetrics {
    return DdrMetricsFromJSONTyped(json, false);
}

export function DdrMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DdrMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'freqMhz': json['freq_mhz'],
    };
}

export function DdrMetricsToJSON(json: any): DdrMetrics {
    return DdrMetricsToJSONTyped(json, false);
}

export function DdrMetricsToJSONTyped(value?: DdrMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'freq_mhz': value['freqMhz'],
    };
}

