/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiskMetrics
 */
export interface DiskMetrics {
    /**
     * 
     * @type {number}
     * @memberof DiskMetrics
     */
    totalBytes: number;
    /**
     * 
     * @type {number}
     * @memberof DiskMetrics
     */
    usedBytes: number;
    /**
     * 
     * @type {number}
     * @memberof DiskMetrics
     */
    freeBytes: number;
    /**
     * 
     * @type {number}
     * @memberof DiskMetrics
     */
    percent: number;
}

/**
 * Check if a given object implements the DiskMetrics interface.
 */
export function instanceOfDiskMetrics(value: object): value is DiskMetrics {
    if (!('totalBytes' in value) || value['totalBytes'] === undefined) return false;
    if (!('usedBytes' in value) || value['usedBytes'] === undefined) return false;
    if (!('freeBytes' in value) || value['freeBytes'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function DiskMetricsFromJSON(json: any): DiskMetrics {
    return DiskMetricsFromJSONTyped(json, false);
}

export function DiskMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBytes': json['total_bytes'],
        'usedBytes': json['used_bytes'],
        'freeBytes': json['free_bytes'],
        'percent': json['percent'],
    };
}

export function DiskMetricsToJSON(json: any): DiskMetrics {
    return DiskMetricsToJSONTyped(json, false);
}

export function DiskMetricsToJSONTyped(value?: DiskMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_bytes': value['totalBytes'],
        'used_bytes': value['usedBytes'],
        'free_bytes': value['freeBytes'],
        'percent': value['percent'],
    };
}

