/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventClipSchema
 */
export interface EventClipSchema {
    /**
     * 
     * @type {string}
     * @memberof EventClipSchema
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof EventClipSchema
     */
    file: string;
    /**
     * 
     * @type {number}
     * @memberof EventClipSchema
     */
    frame_count: number;
    /**
     * 
     * @type {string}
     * @memberof EventClipSchema
     */
    time: string;
    /**
     * 
     * @type {number}
     * @memberof EventClipSchema
     */
    video_id: number;
}

/**
 * Check if a given object implements the EventClipSchema interface.
 */
export function instanceOfEventClipSchema(value: object): value is EventClipSchema {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('frame_count' in value) || value['frame_count'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('video_id' in value) || value['video_id'] === undefined) return false;
    return true;
}

export function EventClipSchemaFromJSON(json: any): EventClipSchema {
    return EventClipSchemaFromJSONTyped(json, false);
}

export function EventClipSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventClipSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'file': json['file'],
        'frame_count': json['frame_count'],
        'time': json['time'],
        'video_id': json['video_id'],
    };
}

export function EventClipSchemaToJSON(json: any): EventClipSchema {
    return EventClipSchemaToJSONTyped(json, false);
}

export function EventClipSchemaToJSONTyped(value?: EventClipSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'file': value['file'],
        'frame_count': value['frame_count'],
        'time': value['time'],
        'video_id': value['video_id'],
    };
}

