/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventRecordingConfigSchemaPatch
 */
export interface EventRecordingConfigSchemaPatch {
    /**
     * 
     * @type {boolean}
     * @memberof EventRecordingConfigSchemaPatch
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchemaPatch
     */
    preBufferSeconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchemaPatch
     */
    postTriggerSeconds?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventRecordingConfigSchemaPatch
     */
    triggerClasses?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchemaPatch
     */
    cooldownSeconds?: number | null;
}

/**
 * Check if a given object implements the EventRecordingConfigSchemaPatch interface.
 */
export function instanceOfEventRecordingConfigSchemaPatch(value: object): value is EventRecordingConfigSchemaPatch {
    return true;
}

export function EventRecordingConfigSchemaPatchFromJSON(json: any): EventRecordingConfigSchemaPatch {
    return EventRecordingConfigSchemaPatchFromJSONTyped(json, false);
}

export function EventRecordingConfigSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventRecordingConfigSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'preBufferSeconds': json['pre_buffer_seconds'] == null ? undefined : json['pre_buffer_seconds'],
        'postTriggerSeconds': json['post_trigger_seconds'] == null ? undefined : json['post_trigger_seconds'],
        'triggerClasses': json['trigger_classes'] == null ? undefined : json['trigger_classes'],
        'cooldownSeconds': json['cooldown_seconds'] == null ? undefined : json['cooldown_seconds'],
    };
}

export function EventRecordingConfigSchemaPatchToJSON(json: any): EventRecordingConfigSchemaPatch {
    return EventRecordingConfigSchemaPatchToJSONTyped(json, false);
}

export function EventRecordingConfigSchemaPatchToJSONTyped(value?: EventRecordingConfigSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'pre_buffer_seconds': value['preBufferSeconds'],
        'post_trigger_seconds': value['postTriggerSeconds'],
        'trigger_classes': value['triggerClasses'],
        'cooldown_seconds': value['cooldownSeconds'],
    };
}

