/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventRecordingConfigSchema
 */
export interface EventRecordingConfigSchema {
    /**
     * 
     * @type {boolean}
     * @memberof EventRecordingConfigSchema
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchema
     */
    preBufferSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchema
     */
    postTriggerSeconds?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventRecordingConfigSchema
     */
    triggerClasses?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof EventRecordingConfigSchema
     */
    cooldownSeconds?: number;
}

/**
 * Check if a given object implements the EventRecordingConfigSchema interface.
 */
export function instanceOfEventRecordingConfigSchema(value: object): value is EventRecordingConfigSchema {
    return true;
}

export function EventRecordingConfigSchemaFromJSON(json: any): EventRecordingConfigSchema {
    return EventRecordingConfigSchemaFromJSONTyped(json, false);
}

export function EventRecordingConfigSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventRecordingConfigSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'preBufferSeconds': json['pre_buffer_seconds'] == null ? undefined : json['pre_buffer_seconds'],
        'postTriggerSeconds': json['post_trigger_seconds'] == null ? undefined : json['post_trigger_seconds'],
        'triggerClasses': json['trigger_classes'] == null ? undefined : json['trigger_classes'],
        'cooldownSeconds': json['cooldown_seconds'] == null ? undefined : json['cooldown_seconds'],
    };
}

export function EventRecordingConfigSchemaToJSON(json: any): EventRecordingConfigSchema {
    return EventRecordingConfigSchemaToJSONTyped(json, false);
}

export function EventRecordingConfigSchemaToJSONTyped(value?: EventRecordingConfigSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'pre_buffer_seconds': value['preBufferSeconds'],
        'post_trigger_seconds': value['postTriggerSeconds'],
        'trigger_classes': value['triggerClasses'],
        'cooldown_seconds': value['cooldownSeconds'],
    };
}

