/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventLogSummary
 */
export interface EventLogSummary {
    /**
     * 
     * @type {string}
     * @memberof EventLogSummary
     */
    eventId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLogSummary
     */
    startedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLogSummary
     */
    endedAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    durationSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    framesTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    framesPrebuffer?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    framesLive?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    detectionsTotal?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventLogSummary
     */
    labels?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof EventLogSummary
     */
    splashes?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventLogSummary
     */
    trigger?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventLogSummary
     */
    configSnapshot?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof EventLogSummary
     */
    uniqueTrackIds?: Array<number>;
}

/**
 * Check if a given object implements the EventLogSummary interface.
 */
export function instanceOfEventLogSummary(value: object): value is EventLogSummary {
    return true;
}

export function EventLogSummaryFromJSON(json: any): EventLogSummary {
    return EventLogSummaryFromJSONTyped(json, false);
}

export function EventLogSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventLogSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'endedAt': json['ended_at'] == null ? undefined : json['ended_at'],
        'durationSeconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'framesTotal': json['frames_total'] == null ? undefined : json['frames_total'],
        'framesPrebuffer': json['frames_prebuffer'] == null ? undefined : json['frames_prebuffer'],
        'framesLive': json['frames_live'] == null ? undefined : json['frames_live'],
        'detectionsTotal': json['detections_total'] == null ? undefined : json['detections_total'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'splashes': json['splashes'] == null ? undefined : json['splashes'],
        'trigger': json['trigger'] == null ? undefined : json['trigger'],
        'configSnapshot': json['config_snapshot'] == null ? undefined : json['config_snapshot'],
        'uniqueTrackIds': json['unique_track_ids'] == null ? undefined : json['unique_track_ids'],
    };
}

export function EventLogSummaryToJSON(json: any): EventLogSummary {
    return EventLogSummaryToJSONTyped(json, false);
}

export function EventLogSummaryToJSONTyped(value?: EventLogSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'started_at': value['startedAt'],
        'ended_at': value['endedAt'],
        'duration_seconds': value['durationSeconds'],
        'frames_total': value['framesTotal'],
        'frames_prebuffer': value['framesPrebuffer'],
        'frames_live': value['framesLive'],
        'detections_total': value['detectionsTotal'],
        'labels': value['labels'],
        'splashes': value['splashes'],
        'trigger': value['trigger'],
        'config_snapshot': value['configSnapshot'],
        'unique_track_ids': value['uniqueTrackIds'],
    };
}

