/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExclusionZoneSchemaPatch
 */
export interface ExclusionZoneSchemaPatch {
    /**
     * 
     * @type {number}
     * @memberof ExclusionZoneSchemaPatch
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ExclusionZoneSchemaPatch
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExclusionZoneSchemaPatch
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {Array<Array<any>>}
     * @memberof ExclusionZoneSchemaPatch
     */
    points?: Array<Array<any>> | null;
}

/**
 * Check if a given object implements the ExclusionZoneSchemaPatch interface.
 */
export function instanceOfExclusionZoneSchemaPatch(value: object): value is ExclusionZoneSchemaPatch {
    return true;
}

export function ExclusionZoneSchemaPatchFromJSON(json: any): ExclusionZoneSchemaPatch {
    return ExclusionZoneSchemaPatchFromJSONTyped(json, false);
}

export function ExclusionZoneSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExclusionZoneSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'points': json['points'] == null ? undefined : json['points'],
    };
}

export function ExclusionZoneSchemaPatchToJSON(json: any): ExclusionZoneSchemaPatch {
    return ExclusionZoneSchemaPatchToJSONTyped(json, false);
}

export function ExclusionZoneSchemaPatchToJSONTyped(value?: ExclusionZoneSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'enabled': value['enabled'],
        'points': value['points'],
    };
}

