/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExclusionZoneSchema
 */
export interface ExclusionZoneSchema {
    /**
     * 
     * @type {number}
     * @memberof ExclusionZoneSchema
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ExclusionZoneSchema
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExclusionZoneSchema
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<Array<any>>}
     * @memberof ExclusionZoneSchema
     */
    points: Array<Array<any>>;
}

/**
 * Check if a given object implements the ExclusionZoneSchema interface.
 */
export function instanceOfExclusionZoneSchema(value: object): value is ExclusionZoneSchema {
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function ExclusionZoneSchemaFromJSON(json: any): ExclusionZoneSchema {
    return ExclusionZoneSchemaFromJSONTyped(json, false);
}

export function ExclusionZoneSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExclusionZoneSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'points': json['points'],
    };
}

export function ExclusionZoneSchemaToJSON(json: any): ExclusionZoneSchema {
    return ExclusionZoneSchemaToJSONTyped(json, false);
}

export function ExclusionZoneSchemaToJSONTyped(value?: ExclusionZoneSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'enabled': value['enabled'],
        'points': value['points'],
    };
}

