/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GpuMetrics
 */
export interface GpuMetrics {
    /**
     * 
     * @type {number}
     * @memberof GpuMetrics
     */
    freqMhz: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpuMetrics
     */
    loadPercent: number | null;
}

/**
 * Check if a given object implements the GpuMetrics interface.
 */
export function instanceOfGpuMetrics(value: object): value is GpuMetrics {
    if (!('freqMhz' in value) || value['freqMhz'] === undefined) return false;
    if (!('loadPercent' in value) || value['loadPercent'] === undefined) return false;
    return true;
}

export function GpuMetricsFromJSON(json: any): GpuMetrics {
    return GpuMetricsFromJSONTyped(json, false);
}

export function GpuMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'freqMhz': json['freq_mhz'],
        'loadPercent': json['load_percent'],
    };
}

export function GpuMetricsToJSON(json: any): GpuMetrics {
    return GpuMetricsToJSONTyped(json, false);
}

export function GpuMetricsToJSONTyped(value?: GpuMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'freq_mhz': value['freqMhz'],
        'load_percent': value['loadPercent'],
    };
}

