/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IspMetrics
 */
export interface IspMetrics {
    /**
     * 
     * @type {number}
     * @memberof IspMetrics
     */
    loadPercent: number | null;
}

/**
 * Check if a given object implements the IspMetrics interface.
 */
export function instanceOfIspMetrics(value: object): value is IspMetrics {
    if (!('loadPercent' in value) || value['loadPercent'] === undefined) return false;
    return true;
}

export function IspMetricsFromJSON(json: any): IspMetrics {
    return IspMetricsFromJSONTyped(json, false);
}

export function IspMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IspMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'loadPercent': json['load_percent'],
    };
}

export function IspMetricsToJSON(json: any): IspMetrics {
    return IspMetricsToJSONTyped(json, false);
}

export function IspMetricsToJSONTyped(value?: IspMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'load_percent': value['loadPercent'],
    };
}

