/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryMetrics
 */
export interface MemoryMetrics {
    /**
     * 
     * @type {number}
     * @memberof MemoryMetrics
     */
    totalBytes: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryMetrics
     */
    availableBytes: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryMetrics
     */
    usedBytes: number;
    /**
     * 
     * @type {number}
     * @memberof MemoryMetrics
     */
    percent: number;
}

/**
 * Check if a given object implements the MemoryMetrics interface.
 */
export function instanceOfMemoryMetrics(value: object): value is MemoryMetrics {
    if (!('totalBytes' in value) || value['totalBytes'] === undefined) return false;
    if (!('availableBytes' in value) || value['availableBytes'] === undefined) return false;
    if (!('usedBytes' in value) || value['usedBytes'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function MemoryMetricsFromJSON(json: any): MemoryMetrics {
    return MemoryMetricsFromJSONTyped(json, false);
}

export function MemoryMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBytes': json['total_bytes'],
        'availableBytes': json['available_bytes'],
        'usedBytes': json['used_bytes'],
        'percent': json['percent'],
    };
}

export function MemoryMetricsToJSON(json: any): MemoryMetrics {
    return MemoryMetricsToJSONTyped(json, false);
}

export function MemoryMetricsToJSONTyped(value?: MemoryMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_bytes': value['totalBytes'],
        'available_bytes': value['availableBytes'],
        'used_bytes': value['usedBytes'],
        'percent': value['percent'],
    };
}

