/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetInterface
 */
export interface NetInterface {
    /**
     * 
     * @type {string}
     * @memberof NetInterface
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NetInterface
     */
    rxBytesPerS: number;
    /**
     * 
     * @type {number}
     * @memberof NetInterface
     */
    txBytesPerS: number;
}

/**
 * Check if a given object implements the NetInterface interface.
 */
export function instanceOfNetInterface(value: object): value is NetInterface {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rxBytesPerS' in value) || value['rxBytesPerS'] === undefined) return false;
    if (!('txBytesPerS' in value) || value['txBytesPerS'] === undefined) return false;
    return true;
}

export function NetInterfaceFromJSON(json: any): NetInterface {
    return NetInterfaceFromJSONTyped(json, false);
}

export function NetInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetInterface {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rxBytesPerS': json['rx_bytes_per_s'],
        'txBytesPerS': json['tx_bytes_per_s'],
    };
}

export function NetInterfaceToJSON(json: any): NetInterface {
    return NetInterfaceToJSONTyped(json, false);
}

export function NetInterfaceToJSONTyped(value?: NetInterface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'rx_bytes_per_s': value['rxBytesPerS'],
        'tx_bytes_per_s': value['txBytesPerS'],
    };
}

