/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetMetrics
 */
export interface NetMetrics {
    /**
     * 
     * @type {number}
     * @memberof NetMetrics
     */
    rxBytesPerS: number;
    /**
     * 
     * @type {number}
     * @memberof NetMetrics
     */
    txBytesPerS: number;
}

/**
 * Check if a given object implements the NetMetrics interface.
 */
export function instanceOfNetMetrics(value: object): value is NetMetrics {
    if (!('rxBytesPerS' in value) || value['rxBytesPerS'] === undefined) return false;
    if (!('txBytesPerS' in value) || value['txBytesPerS'] === undefined) return false;
    return true;
}

export function NetMetricsFromJSON(json: any): NetMetrics {
    return NetMetricsFromJSONTyped(json, false);
}

export function NetMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'rxBytesPerS': json['rx_bytes_per_s'],
        'txBytesPerS': json['tx_bytes_per_s'],
    };
}

export function NetMetricsToJSON(json: any): NetMetrics {
    return NetMetricsToJSONTyped(json, false);
}

export function NetMetricsToJSONTyped(value?: NetMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rx_bytes_per_s': value['rxBytesPerS'],
        'tx_bytes_per_s': value['txBytesPerS'],
    };
}

