/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PikiOptions
 */
export interface PikiOptions {
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    showBoxes?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    confThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    confThresholdKeep?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    minConsecutiveFrames?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    bboxEmaAlpha?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    trackerEnabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    trackerIouThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    trackerMaxMisses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    trackerConfirmHits?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    trackerDeltaT?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    trackerInertia?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    pixelcountThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    minArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2History?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2VarThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    denoiseKernelsize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKi?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoDeadZone?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoKalmanProcessNoise?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoKalmanMeasNoise?: number | null;
}

/**
 * Check if a given object implements the PikiOptions interface.
 */
export function instanceOfPikiOptions(value: object): value is PikiOptions {
    return true;
}

export function PikiOptionsFromJSON(json: any): PikiOptions {
    return PikiOptionsFromJSONTyped(json, false);
}

export function PikiOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PikiOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'showBoxes': json['show_boxes'] == null ? undefined : json['show_boxes'],
        'confThreshold': json['conf_threshold'] == null ? undefined : json['conf_threshold'],
        'confThresholdKeep': json['conf_threshold_keep'] == null ? undefined : json['conf_threshold_keep'],
        'minConsecutiveFrames': json['min_consecutive_frames'] == null ? undefined : json['min_consecutive_frames'],
        'bboxEmaAlpha': json['bbox_ema_alpha'] == null ? undefined : json['bbox_ema_alpha'],
        'trackerEnabled': json['tracker_enabled'] == null ? undefined : json['tracker_enabled'],
        'trackerIouThreshold': json['tracker_iou_threshold'] == null ? undefined : json['tracker_iou_threshold'],
        'trackerMaxMisses': json['tracker_max_misses'] == null ? undefined : json['tracker_max_misses'],
        'trackerConfirmHits': json['tracker_confirm_hits'] == null ? undefined : json['tracker_confirm_hits'],
        'trackerDeltaT': json['tracker_delta_t'] == null ? undefined : json['tracker_delta_t'],
        'trackerInertia': json['tracker_inertia'] == null ? undefined : json['tracker_inertia'],
        'pixelcountThreshold': json['pixelcount_threshold'] == null ? undefined : json['pixelcount_threshold'],
        'minArea': json['min_area'] == null ? undefined : json['min_area'],
        'mog2History': json['mog2_history'] == null ? undefined : json['mog2_history'],
        'mog2VarThreshold': json['mog2_var_threshold'] == null ? undefined : json['mog2_var_threshold'],
        'denoiseKernelsize': json['denoise_kernelsize'] == null ? undefined : json['denoise_kernelsize'],
        'servoPidKp': json['servo_pid_kp'] == null ? undefined : json['servo_pid_kp'],
        'servoPidKi': json['servo_pid_ki'] == null ? undefined : json['servo_pid_ki'],
        'servoPidKd': json['servo_pid_kd'] == null ? undefined : json['servo_pid_kd'],
        'servoDeadZone': json['servo_dead_zone'] == null ? undefined : json['servo_dead_zone'],
        'servoKalmanProcessNoise': json['servo_kalman_process_noise'] == null ? undefined : json['servo_kalman_process_noise'],
        'servoKalmanMeasNoise': json['servo_kalman_meas_noise'] == null ? undefined : json['servo_kalman_meas_noise'],
    };
}

export function PikiOptionsToJSON(json: any): PikiOptions {
    return PikiOptionsToJSONTyped(json, false);
}

export function PikiOptionsToJSONTyped(value?: PikiOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'show_boxes': value['showBoxes'],
        'conf_threshold': value['confThreshold'],
        'conf_threshold_keep': value['confThresholdKeep'],
        'min_consecutive_frames': value['minConsecutiveFrames'],
        'bbox_ema_alpha': value['bboxEmaAlpha'],
        'tracker_enabled': value['trackerEnabled'],
        'tracker_iou_threshold': value['trackerIouThreshold'],
        'tracker_max_misses': value['trackerMaxMisses'],
        'tracker_confirm_hits': value['trackerConfirmHits'],
        'tracker_delta_t': value['trackerDeltaT'],
        'tracker_inertia': value['trackerInertia'],
        'pixelcount_threshold': value['pixelcountThreshold'],
        'min_area': value['minArea'],
        'mog2_history': value['mog2History'],
        'mog2_var_threshold': value['mog2VarThreshold'],
        'denoise_kernelsize': value['denoiseKernelsize'],
        'servo_pid_kp': value['servoPidKp'],
        'servo_pid_ki': value['servoPidKi'],
        'servo_pid_kd': value['servoPidKd'],
        'servo_dead_zone': value['servoDeadZone'],
        'servo_kalman_process_noise': value['servoKalmanProcessNoise'],
        'servo_kalman_meas_noise': value['servoKalmanMeasNoise'],
    };
}

