/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PikiOptions
 */
export interface PikiOptions {
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    show_boxes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    show_mask?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    show_rois?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    show_seg?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    conf_threshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    pixelcount_threshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    min_area?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2_history?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2_var_threshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    denoise_kernelsize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mask_transparency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servo_pid_kp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servo_pid_ki?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servo_pid_kd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servo_dead_zone?: number | null;
}

/**
 * Check if a given object implements the PikiOptions interface.
 */
export function instanceOfPikiOptions(value: object): value is PikiOptions {
    return true;
}

export function PikiOptionsFromJSON(json: any): PikiOptions {
    return PikiOptionsFromJSONTyped(json, false);
}

export function PikiOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PikiOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'show_boxes': json['show_boxes'] == null ? undefined : json['show_boxes'],
        'show_mask': json['show_mask'] == null ? undefined : json['show_mask'],
        'show_rois': json['show_rois'] == null ? undefined : json['show_rois'],
        'show_seg': json['show_seg'] == null ? undefined : json['show_seg'],
        'conf_threshold': json['conf_threshold'] == null ? undefined : json['conf_threshold'],
        'pixelcount_threshold': json['pixelcount_threshold'] == null ? undefined : json['pixelcount_threshold'],
        'min_area': json['min_area'] == null ? undefined : json['min_area'],
        'mog2_history': json['mog2_history'] == null ? undefined : json['mog2_history'],
        'mog2_var_threshold': json['mog2_var_threshold'] == null ? undefined : json['mog2_var_threshold'],
        'denoise_kernelsize': json['denoise_kernelsize'] == null ? undefined : json['denoise_kernelsize'],
        'mask_transparency': json['mask_transparency'] == null ? undefined : json['mask_transparency'],
        'servo_pid_kp': json['servo_pid_kp'] == null ? undefined : json['servo_pid_kp'],
        'servo_pid_ki': json['servo_pid_ki'] == null ? undefined : json['servo_pid_ki'],
        'servo_pid_kd': json['servo_pid_kd'] == null ? undefined : json['servo_pid_kd'],
        'servo_dead_zone': json['servo_dead_zone'] == null ? undefined : json['servo_dead_zone'],
    };
}

export function PikiOptionsToJSON(json: any): PikiOptions {
    return PikiOptionsToJSONTyped(json, false);
}

export function PikiOptionsToJSONTyped(value?: PikiOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'show_boxes': value['show_boxes'],
        'show_mask': value['show_mask'],
        'show_rois': value['show_rois'],
        'show_seg': value['show_seg'],
        'conf_threshold': value['conf_threshold'],
        'pixelcount_threshold': value['pixelcount_threshold'],
        'min_area': value['min_area'],
        'mog2_history': value['mog2_history'],
        'mog2_var_threshold': value['mog2_var_threshold'],
        'denoise_kernelsize': value['denoise_kernelsize'],
        'mask_transparency': value['mask_transparency'],
        'servo_pid_kp': value['servo_pid_kp'],
        'servo_pid_ki': value['servo_pid_ki'],
        'servo_pid_kd': value['servo_pid_kd'],
        'servo_dead_zone': value['servo_dead_zone'],
    };
}

