/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PikiOptions
 */
export interface PikiOptions {
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    showBoxes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    showMask?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptions
     */
    showRois?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    confThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    pixelcountThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    minArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2History?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    mog2VarThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    denoiseKernelsize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    maskTransparency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKi?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoPidKd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptions
     */
    servoDeadZone?: number | null;
}

/**
 * Check if a given object implements the PikiOptions interface.
 */
export function instanceOfPikiOptions(value: object): value is PikiOptions {
    return true;
}

export function PikiOptionsFromJSON(json: any): PikiOptions {
    return PikiOptionsFromJSONTyped(json, false);
}

export function PikiOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PikiOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'showBoxes': json['show_boxes'] == null ? undefined : json['show_boxes'],
        'showMask': json['show_mask'] == null ? undefined : json['show_mask'],
        'showRois': json['show_rois'] == null ? undefined : json['show_rois'],
        'confThreshold': json['conf_threshold'] == null ? undefined : json['conf_threshold'],
        'pixelcountThreshold': json['pixelcount_threshold'] == null ? undefined : json['pixelcount_threshold'],
        'minArea': json['min_area'] == null ? undefined : json['min_area'],
        'mog2History': json['mog2_history'] == null ? undefined : json['mog2_history'],
        'mog2VarThreshold': json['mog2_var_threshold'] == null ? undefined : json['mog2_var_threshold'],
        'denoiseKernelsize': json['denoise_kernelsize'] == null ? undefined : json['denoise_kernelsize'],
        'maskTransparency': json['mask_transparency'] == null ? undefined : json['mask_transparency'],
        'servoPidKp': json['servo_pid_kp'] == null ? undefined : json['servo_pid_kp'],
        'servoPidKi': json['servo_pid_ki'] == null ? undefined : json['servo_pid_ki'],
        'servoPidKd': json['servo_pid_kd'] == null ? undefined : json['servo_pid_kd'],
        'servoDeadZone': json['servo_dead_zone'] == null ? undefined : json['servo_dead_zone'],
    };
}

export function PikiOptionsToJSON(json: any): PikiOptions {
    return PikiOptionsToJSONTyped(json, false);
}

export function PikiOptionsToJSONTyped(value?: PikiOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'show_boxes': value['showBoxes'],
        'show_mask': value['showMask'],
        'show_rois': value['showRois'],
        'conf_threshold': value['confThreshold'],
        'pixelcount_threshold': value['pixelcountThreshold'],
        'min_area': value['minArea'],
        'mog2_history': value['mog2History'],
        'mog2_var_threshold': value['mog2VarThreshold'],
        'denoise_kernelsize': value['denoiseKernelsize'],
        'mask_transparency': value['maskTransparency'],
        'servo_pid_kp': value['servoPidKp'],
        'servo_pid_ki': value['servoPidKi'],
        'servo_pid_kd': value['servoPidKd'],
        'servo_dead_zone': value['servoDeadZone'],
    };
}

