/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PikiOptionsPatch
 */
export interface PikiOptionsPatch {
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptionsPatch
     */
    showBoxes?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptionsPatch
     */
    showMask?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptionsPatch
     */
    showRois?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    confThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    confThresholdKeep?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    minConsecutiveFrames?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    bboxEmaAlpha?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    ghostFramesMs?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptionsPatch
     */
    trackerEnabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    trackerIouThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    trackerMaxMisses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    trackerConfirmHits?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PikiOptionsPatch
     */
    trackerReidEnabled?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    trackerReidThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    trackerReidHitCounterMax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    pixelcountThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    minArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    mog2History?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    mog2VarThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    denoiseKernelsize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    maskTransparency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoPidKp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoPidKi?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoPidKd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoDeadZone?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoKalmanProcessNoise?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    servoKalmanMeasNoise?: number | null;
}

/**
 * Check if a given object implements the PikiOptionsPatch interface.
 */
export function instanceOfPikiOptionsPatch(value: object): value is PikiOptionsPatch {
    return true;
}

export function PikiOptionsPatchFromJSON(json: any): PikiOptionsPatch {
    return PikiOptionsPatchFromJSONTyped(json, false);
}

export function PikiOptionsPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PikiOptionsPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'showBoxes': json['show_boxes'] == null ? undefined : json['show_boxes'],
        'showMask': json['show_mask'] == null ? undefined : json['show_mask'],
        'showRois': json['show_rois'] == null ? undefined : json['show_rois'],
        'confThreshold': json['conf_threshold'] == null ? undefined : json['conf_threshold'],
        'confThresholdKeep': json['conf_threshold_keep'] == null ? undefined : json['conf_threshold_keep'],
        'minConsecutiveFrames': json['min_consecutive_frames'] == null ? undefined : json['min_consecutive_frames'],
        'bboxEmaAlpha': json['bbox_ema_alpha'] == null ? undefined : json['bbox_ema_alpha'],
        'ghostFramesMs': json['ghost_frames_ms'] == null ? undefined : json['ghost_frames_ms'],
        'trackerEnabled': json['tracker_enabled'] == null ? undefined : json['tracker_enabled'],
        'trackerIouThreshold': json['tracker_iou_threshold'] == null ? undefined : json['tracker_iou_threshold'],
        'trackerMaxMisses': json['tracker_max_misses'] == null ? undefined : json['tracker_max_misses'],
        'trackerConfirmHits': json['tracker_confirm_hits'] == null ? undefined : json['tracker_confirm_hits'],
        'trackerReidEnabled': json['tracker_reid_enabled'] == null ? undefined : json['tracker_reid_enabled'],
        'trackerReidThreshold': json['tracker_reid_threshold'] == null ? undefined : json['tracker_reid_threshold'],
        'trackerReidHitCounterMax': json['tracker_reid_hit_counter_max'] == null ? undefined : json['tracker_reid_hit_counter_max'],
        'pixelcountThreshold': json['pixelcount_threshold'] == null ? undefined : json['pixelcount_threshold'],
        'minArea': json['min_area'] == null ? undefined : json['min_area'],
        'mog2History': json['mog2_history'] == null ? undefined : json['mog2_history'],
        'mog2VarThreshold': json['mog2_var_threshold'] == null ? undefined : json['mog2_var_threshold'],
        'denoiseKernelsize': json['denoise_kernelsize'] == null ? undefined : json['denoise_kernelsize'],
        'maskTransparency': json['mask_transparency'] == null ? undefined : json['mask_transparency'],
        'servoPidKp': json['servo_pid_kp'] == null ? undefined : json['servo_pid_kp'],
        'servoPidKi': json['servo_pid_ki'] == null ? undefined : json['servo_pid_ki'],
        'servoPidKd': json['servo_pid_kd'] == null ? undefined : json['servo_pid_kd'],
        'servoDeadZone': json['servo_dead_zone'] == null ? undefined : json['servo_dead_zone'],
        'servoKalmanProcessNoise': json['servo_kalman_process_noise'] == null ? undefined : json['servo_kalman_process_noise'],
        'servoKalmanMeasNoise': json['servo_kalman_meas_noise'] == null ? undefined : json['servo_kalman_meas_noise'],
    };
}

export function PikiOptionsPatchToJSON(json: any): PikiOptionsPatch {
    return PikiOptionsPatchToJSONTyped(json, false);
}

export function PikiOptionsPatchToJSONTyped(value?: PikiOptionsPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'show_boxes': value['showBoxes'],
        'show_mask': value['showMask'],
        'show_rois': value['showRois'],
        'conf_threshold': value['confThreshold'],
        'conf_threshold_keep': value['confThresholdKeep'],
        'min_consecutive_frames': value['minConsecutiveFrames'],
        'bbox_ema_alpha': value['bboxEmaAlpha'],
        'ghost_frames_ms': value['ghostFramesMs'],
        'tracker_enabled': value['trackerEnabled'],
        'tracker_iou_threshold': value['trackerIouThreshold'],
        'tracker_max_misses': value['trackerMaxMisses'],
        'tracker_confirm_hits': value['trackerConfirmHits'],
        'tracker_reid_enabled': value['trackerReidEnabled'],
        'tracker_reid_threshold': value['trackerReidThreshold'],
        'tracker_reid_hit_counter_max': value['trackerReidHitCounterMax'],
        'pixelcount_threshold': value['pixelcountThreshold'],
        'min_area': value['minArea'],
        'mog2_history': value['mog2History'],
        'mog2_var_threshold': value['mog2VarThreshold'],
        'denoise_kernelsize': value['denoiseKernelsize'],
        'mask_transparency': value['maskTransparency'],
        'servo_pid_kp': value['servoPidKp'],
        'servo_pid_ki': value['servoPidKi'],
        'servo_pid_kd': value['servoPidKd'],
        'servo_dead_zone': value['servoDeadZone'],
        'servo_kalman_process_noise': value['servoKalmanProcessNoise'],
        'servo_kalman_meas_noise': value['servoKalmanMeasNoise'],
    };
}

