/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PikiOptionsPatch
 */
export interface PikiOptionsPatch {
    /**
     * 
     * @type {string}
     * @memberof PikiOptionsPatch
     */
    mode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    confThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    pixelcountThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PikiOptionsPatch
     */
    minArea?: number | null;
}

/**
 * Check if a given object implements the PikiOptionsPatch interface.
 */
export function instanceOfPikiOptionsPatch(value: object): value is PikiOptionsPatch {
    return true;
}

export function PikiOptionsPatchFromJSON(json: any): PikiOptionsPatch {
    return PikiOptionsPatchFromJSONTyped(json, false);
}

export function PikiOptionsPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PikiOptionsPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
        'confThreshold': json['conf_threshold'] == null ? undefined : json['conf_threshold'],
        'pixelcountThreshold': json['pixelcount_threshold'] == null ? undefined : json['pixelcount_threshold'],
        'minArea': json['min_area'] == null ? undefined : json['min_area'],
    };
}

export function PikiOptionsPatchToJSON(json: any): PikiOptionsPatch {
    return PikiOptionsPatchToJSONTyped(json, false);
}

export function PikiOptionsPatchToJSONTyped(value?: PikiOptionsPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'conf_threshold': value['confThreshold'],
        'pixelcount_threshold': value['pixelcountThreshold'],
        'min_area': value['minArea'],
    };
}

