/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordingStatus
 */
export interface RecordingStatus {
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    isRecording: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    elapsedSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    frameCount?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordingStatus
     */
    filePath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    eventEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    eventActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    eventCooldownRemaining?: number;
}

/**
 * Check if a given object implements the RecordingStatus interface.
 */
export function instanceOfRecordingStatus(value: object): value is RecordingStatus {
    if (!('isRecording' in value) || value['isRecording'] === undefined) return false;
    return true;
}

export function RecordingStatusFromJSON(json: any): RecordingStatus {
    return RecordingStatusFromJSONTyped(json, false);
}

export function RecordingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordingStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'isRecording': json['is_recording'],
        'elapsedSeconds': json['elapsed_seconds'] == null ? undefined : json['elapsed_seconds'],
        'frameCount': json['frame_count'] == null ? undefined : json['frame_count'],
        'filePath': json['file_path'] == null ? undefined : json['file_path'],
        'eventEnabled': json['event_enabled'] == null ? undefined : json['event_enabled'],
        'eventActive': json['event_active'] == null ? undefined : json['event_active'],
        'eventCooldownRemaining': json['event_cooldown_remaining'] == null ? undefined : json['event_cooldown_remaining'],
    };
}

export function RecordingStatusToJSON(json: any): RecordingStatus {
    return RecordingStatusToJSONTyped(json, false);
}

export function RecordingStatusToJSONTyped(value?: RecordingStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_recording': value['isRecording'],
        'elapsed_seconds': value['elapsedSeconds'],
        'frame_count': value['frameCount'],
        'file_path': value['filePath'],
        'event_enabled': value['eventEnabled'],
        'event_active': value['eventActive'],
        'event_cooldown_remaining': value['eventCooldownRemaining'],
    };
}

