/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordingStatus
 */
export interface RecordingStatus {
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    is_recording: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    elapsed_seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    frame_count?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordingStatus
     */
    file_path?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    event_enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingStatus
     */
    event_active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecordingStatus
     */
    event_cooldown_remaining?: number;
}

/**
 * Check if a given object implements the RecordingStatus interface.
 */
export function instanceOfRecordingStatus(value: object): value is RecordingStatus {
    if (!('is_recording' in value) || value['is_recording'] === undefined) return false;
    return true;
}

export function RecordingStatusFromJSON(json: any): RecordingStatus {
    return RecordingStatusFromJSONTyped(json, false);
}

export function RecordingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordingStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'is_recording': json['is_recording'],
        'elapsed_seconds': json['elapsed_seconds'] == null ? undefined : json['elapsed_seconds'],
        'frame_count': json['frame_count'] == null ? undefined : json['frame_count'],
        'file_path': json['file_path'] == null ? undefined : json['file_path'],
        'event_enabled': json['event_enabled'] == null ? undefined : json['event_enabled'],
        'event_active': json['event_active'] == null ? undefined : json['event_active'],
        'event_cooldown_remaining': json['event_cooldown_remaining'] == null ? undefined : json['event_cooldown_remaining'],
    };
}

export function RecordingStatusToJSON(json: any): RecordingStatus {
    return RecordingStatusToJSONTyped(json, false);
}

export function RecordingStatusToJSONTyped(value?: RecordingStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_recording': value['is_recording'],
        'elapsed_seconds': value['elapsed_seconds'],
        'frame_count': value['frame_count'],
        'file_path': value['file_path'],
        'event_enabled': value['event_enabled'],
        'event_active': value['event_active'],
        'event_cooldown_remaining': value['event_cooldown_remaining'],
    };
}

