/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayStatus
 */
export interface ReplayStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ReplayStatus
     */
    isReplaying: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReplayStatus
     */
    videoFilename?: string;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    currentFrame?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    totalFrames?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    videoFps?: number;
}

/**
 * Check if a given object implements the ReplayStatus interface.
 */
export function instanceOfReplayStatus(value: object): value is ReplayStatus {
    if (!('isReplaying' in value) || value['isReplaying'] === undefined) return false;
    return true;
}

export function ReplayStatusFromJSON(json: any): ReplayStatus {
    return ReplayStatusFromJSONTyped(json, false);
}

export function ReplayStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'isReplaying': json['is_replaying'],
        'videoFilename': json['video_filename'] == null ? undefined : json['video_filename'],
        'currentFrame': json['current_frame'] == null ? undefined : json['current_frame'],
        'totalFrames': json['total_frames'] == null ? undefined : json['total_frames'],
        'videoFps': json['video_fps'] == null ? undefined : json['video_fps'],
    };
}

export function ReplayStatusToJSON(json: any): ReplayStatus {
    return ReplayStatusToJSONTyped(json, false);
}

export function ReplayStatusToJSONTyped(value?: ReplayStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_replaying': value['isReplaying'],
        'video_filename': value['videoFilename'],
        'current_frame': value['currentFrame'],
        'total_frames': value['totalFrames'],
        'video_fps': value['videoFps'],
    };
}

