/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayStatus
 */
export interface ReplayStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ReplayStatus
     */
    is_replaying: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReplayStatus
     */
    video_filename?: string;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    current_frame?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    total_frames?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplayStatus
     */
    video_fps?: number;
}

/**
 * Check if a given object implements the ReplayStatus interface.
 */
export function instanceOfReplayStatus(value: object): value is ReplayStatus {
    if (!('is_replaying' in value) || value['is_replaying'] === undefined) return false;
    return true;
}

export function ReplayStatusFromJSON(json: any): ReplayStatus {
    return ReplayStatusFromJSONTyped(json, false);
}

export function ReplayStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'is_replaying': json['is_replaying'],
        'video_filename': json['video_filename'] == null ? undefined : json['video_filename'],
        'current_frame': json['current_frame'] == null ? undefined : json['current_frame'],
        'total_frames': json['total_frames'] == null ? undefined : json['total_frames'],
        'video_fps': json['video_fps'] == null ? undefined : json['video_fps'],
    };
}

export function ReplayStatusToJSON(json: any): ReplayStatus {
    return ReplayStatusToJSONTyped(json, false);
}

export function ReplayStatusToJSONTyped(value?: ReplayStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_replaying': value['is_replaying'],
        'video_filename': value['video_filename'],
        'current_frame': value['current_frame'],
        'total_frames': value['total_frames'],
        'video_fps': value['video_fps'],
    };
}

