/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServoMoveSchema
 */
export interface ServoMoveSchema {
    /**
     * 
     * @type {number}
     * @memberof ServoMoveSchema
     */
    panAngle: number;
    /**
     * 
     * @type {number}
     * @memberof ServoMoveSchema
     */
    tiltAngle: number;
}

/**
 * Check if a given object implements the ServoMoveSchema interface.
 */
export function instanceOfServoMoveSchema(value: object): value is ServoMoveSchema {
    if (!('panAngle' in value) || value['panAngle'] === undefined) return false;
    if (!('tiltAngle' in value) || value['tiltAngle'] === undefined) return false;
    return true;
}

export function ServoMoveSchemaFromJSON(json: any): ServoMoveSchema {
    return ServoMoveSchemaFromJSONTyped(json, false);
}

export function ServoMoveSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServoMoveSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'panAngle': json['pan_angle'],
        'tiltAngle': json['tilt_angle'],
    };
}

export function ServoMoveSchemaToJSON(json: any): ServoMoveSchema {
    return ServoMoveSchemaToJSONTyped(json, false);
}

export function ServoMoveSchemaToJSONTyped(value?: ServoMoveSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pan_angle': value['panAngle'],
        'tilt_angle': value['tiltAngle'],
    };
}

