/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServoStateSchema
 */
export interface ServoStateSchema {
    /**
     * 
     * @type {number}
     * @memberof ServoStateSchema
     */
    pan: number;
    /**
     * 
     * @type {number}
     * @memberof ServoStateSchema
     */
    tilt: number;
    /**
     * 
     * @type {number}
     * @memberof ServoStateSchema
     */
    kalmanPan: number;
    /**
     * 
     * @type {number}
     * @memberof ServoStateSchema
     */
    kalmanTilt: number;
}

/**
 * Check if a given object implements the ServoStateSchema interface.
 */
export function instanceOfServoStateSchema(value: object): value is ServoStateSchema {
    if (!('pan' in value) || value['pan'] === undefined) return false;
    if (!('tilt' in value) || value['tilt'] === undefined) return false;
    if (!('kalmanPan' in value) || value['kalmanPan'] === undefined) return false;
    if (!('kalmanTilt' in value) || value['kalmanTilt'] === undefined) return false;
    return true;
}

export function ServoStateSchemaFromJSON(json: any): ServoStateSchema {
    return ServoStateSchemaFromJSONTyped(json, false);
}

export function ServoStateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServoStateSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'pan': json['pan'],
        'tilt': json['tilt'],
        'kalmanPan': json['kalman_pan'],
        'kalmanTilt': json['kalman_tilt'],
    };
}

export function ServoStateSchemaToJSON(json: any): ServoStateSchema {
    return ServoStateSchemaToJSONTyped(json, false);
}

export function ServoStateSchemaToJSONTyped(value?: ServoStateSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pan': value['pan'],
        'tilt': value['tilt'],
        'kalman_pan': value['kalmanPan'],
        'kalman_tilt': value['kalmanTilt'],
    };
}

