/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServoPositionSchema
 */
export interface ServoPositionSchema {
    /**
     * 
     * @type {number}
     * @memberof ServoPositionSchema
     */
    pan_angle: number;
    /**
     * 
     * @type {number}
     * @memberof ServoPositionSchema
     */
    tilt_angle: number;
}

/**
 * Check if a given object implements the ServoPositionSchema interface.
 */
export function instanceOfServoPositionSchema(value: object): value is ServoPositionSchema {
    if (!('pan_angle' in value) || value['pan_angle'] === undefined) return false;
    if (!('tilt_angle' in value) || value['tilt_angle'] === undefined) return false;
    return true;
}

export function ServoPositionSchemaFromJSON(json: any): ServoPositionSchema {
    return ServoPositionSchemaFromJSONTyped(json, false);
}

export function ServoPositionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServoPositionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'pan_angle': json['pan_angle'],
        'tilt_angle': json['tilt_angle'],
    };
}

export function ServoPositionSchemaToJSON(json: any): ServoPositionSchema {
    return ServoPositionSchemaToJSONTyped(json, false);
}

export function ServoPositionSchemaToJSONTyped(value?: ServoPositionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pan_angle': value['pan_angle'],
        'tilt_angle': value['tilt_angle'],
    };
}

