/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplashConfigSchemaPatch
 */
export interface SplashConfigSchemaPatch {
    /**
     * 
     * @type {boolean}
     * @memberof SplashConfigSchemaPatch
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SplashConfigSchemaPatch
     */
    trigger_classes?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchemaPatch
     */
    delay_seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchemaPatch
     */
    duration_seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchemaPatch
     */
    cooldown_seconds?: number | null;
}

/**
 * Check if a given object implements the SplashConfigSchemaPatch interface.
 */
export function instanceOfSplashConfigSchemaPatch(value: object): value is SplashConfigSchemaPatch {
    return true;
}

export function SplashConfigSchemaPatchFromJSON(json: any): SplashConfigSchemaPatch {
    return SplashConfigSchemaPatchFromJSONTyped(json, false);
}

export function SplashConfigSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplashConfigSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'trigger_classes': json['trigger_classes'] == null ? undefined : json['trigger_classes'],
        'delay_seconds': json['delay_seconds'] == null ? undefined : json['delay_seconds'],
        'duration_seconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'cooldown_seconds': json['cooldown_seconds'] == null ? undefined : json['cooldown_seconds'],
    };
}

export function SplashConfigSchemaPatchToJSON(json: any): SplashConfigSchemaPatch {
    return SplashConfigSchemaPatchToJSONTyped(json, false);
}

export function SplashConfigSchemaPatchToJSONTyped(value?: SplashConfigSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'trigger_classes': value['trigger_classes'],
        'delay_seconds': value['delay_seconds'],
        'duration_seconds': value['duration_seconds'],
        'cooldown_seconds': value['cooldown_seconds'],
    };
}

