/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplashActivateResponse
 */
export interface SplashActivateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SplashActivateResponse
     */
    ok?: boolean;
}

/**
 * Check if a given object implements the SplashActivateResponse interface.
 */
export function instanceOfSplashActivateResponse(value: object): value is SplashActivateResponse {
    return true;
}

export function SplashActivateResponseFromJSON(json: any): SplashActivateResponse {
    return SplashActivateResponseFromJSONTyped(json, false);
}

export function SplashActivateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplashActivateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
    };
}

export function SplashActivateResponseToJSON(json: any): SplashActivateResponse {
    return SplashActivateResponseToJSONTyped(json, false);
}

export function SplashActivateResponseToJSONTyped(value?: SplashActivateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

