/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplashStatus
 */
export interface SplashStatus {
    /**
     * 
     * @type {string}
     * @memberof SplashStatus
     */
    state?: string;
    /**
     * 
     * @type {number}
     * @memberof SplashStatus
     */
    delayRemaining?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashStatus
     */
    firingRemaining?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashStatus
     */
    cooldownRemaining?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashStatus
     */
    firingDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashStatus
     */
    cooldownDuration?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SplashStatus
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the SplashStatus interface.
 */
export function instanceOfSplashStatus(value: object): value is SplashStatus {
    return true;
}

export function SplashStatusFromJSON(json: any): SplashStatus {
    return SplashStatusFromJSONTyped(json, false);
}

export function SplashStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplashStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
        'delayRemaining': json['delay_remaining'] == null ? undefined : json['delay_remaining'],
        'firingRemaining': json['firing_remaining'] == null ? undefined : json['firing_remaining'],
        'cooldownRemaining': json['cooldown_remaining'] == null ? undefined : json['cooldown_remaining'],
        'firingDuration': json['firing_duration'] == null ? undefined : json['firing_duration'],
        'cooldownDuration': json['cooldown_duration'] == null ? undefined : json['cooldown_duration'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function SplashStatusToJSON(json: any): SplashStatus {
    return SplashStatusToJSONTyped(json, false);
}

export function SplashStatusToJSONTyped(value?: SplashStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'delay_remaining': value['delayRemaining'],
        'firing_remaining': value['firingRemaining'],
        'cooldown_remaining': value['cooldownRemaining'],
        'firing_duration': value['firingDuration'],
        'cooldown_duration': value['cooldownDuration'],
        'enabled': value['enabled'],
    };
}

