/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplashConfigSchema
 */
export interface SplashConfigSchema {
    /**
     * 
     * @type {boolean}
     * @memberof SplashConfigSchema
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SplashConfigSchema
     */
    trigger_classes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchema
     */
    delay_seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchema
     */
    duration_seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof SplashConfigSchema
     */
    cooldown_seconds?: number;
}

/**
 * Check if a given object implements the SplashConfigSchema interface.
 */
export function instanceOfSplashConfigSchema(value: object): value is SplashConfigSchema {
    return true;
}

export function SplashConfigSchemaFromJSON(json: any): SplashConfigSchema {
    return SplashConfigSchemaFromJSONTyped(json, false);
}

export function SplashConfigSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplashConfigSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'trigger_classes': json['trigger_classes'] == null ? undefined : json['trigger_classes'],
        'delay_seconds': json['delay_seconds'] == null ? undefined : json['delay_seconds'],
        'duration_seconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'cooldown_seconds': json['cooldown_seconds'] == null ? undefined : json['cooldown_seconds'],
    };
}

export function SplashConfigSchemaToJSON(json: any): SplashConfigSchema {
    return SplashConfigSchemaToJSONTyped(json, false);
}

export function SplashConfigSchemaToJSONTyped(value?: SplashConfigSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'trigger_classes': value['trigger_classes'],
        'delay_seconds': value['delay_seconds'],
        'duration_seconds': value['duration_seconds'],
        'cooldown_seconds': value['cooldown_seconds'],
    };
}

