/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwapMetrics
 */
export interface SwapMetrics {
    /**
     * 
     * @type {number}
     * @memberof SwapMetrics
     */
    totalBytes: number;
    /**
     * 
     * @type {number}
     * @memberof SwapMetrics
     */
    usedBytes: number;
    /**
     * 
     * @type {number}
     * @memberof SwapMetrics
     */
    percent: number;
}

/**
 * Check if a given object implements the SwapMetrics interface.
 */
export function instanceOfSwapMetrics(value: object): value is SwapMetrics {
    if (!('totalBytes' in value) || value['totalBytes'] === undefined) return false;
    if (!('usedBytes' in value) || value['usedBytes'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function SwapMetricsFromJSON(json: any): SwapMetrics {
    return SwapMetricsFromJSONTyped(json, false);
}

export function SwapMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBytes': json['total_bytes'],
        'usedBytes': json['used_bytes'],
        'percent': json['percent'],
    };
}

export function SwapMetricsToJSON(json: any): SwapMetrics {
    return SwapMetricsToJSONTyped(json, false);
}

export function SwapMetricsToJSONTyped(value?: SwapMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_bytes': value['totalBytes'],
        'used_bytes': value['usedBytes'],
        'percent': value['percent'],
    };
}

