/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemStatus
 */
export interface SystemStatus {
    /**
     * 
     * @type {number}
     * @memberof SystemStatus
     */
    fps: number;
}

/**
 * Check if a given object implements the SystemStatus interface.
 */
export function instanceOfSystemStatus(value: object): value is SystemStatus {
    if (!('fps' in value) || value['fps'] === undefined) return false;
    return true;
}

export function SystemStatusFromJSON(json: any): SystemStatus {
    return SystemStatusFromJSONTyped(json, false);
}

export function SystemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'fps': json['fps'],
    };
}

export function SystemStatusToJSON(json: any): SystemStatus {
    return SystemStatusToJSONTyped(json, false);
}

export function SystemStatusToJSONTyped(value?: SystemStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fps': value['fps'],
    };
}

