/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemoryMetrics } from './MemoryMetrics';
import {
    MemoryMetricsFromJSON,
    MemoryMetricsFromJSONTyped,
    MemoryMetricsToJSON,
    MemoryMetricsToJSONTyped,
} from './MemoryMetrics';
import type { CoolingDevice } from './CoolingDevice';
import {
    CoolingDeviceFromJSON,
    CoolingDeviceFromJSONTyped,
    CoolingDeviceToJSON,
    CoolingDeviceToJSONTyped,
} from './CoolingDevice';
import type { DdrMetrics } from './DdrMetrics';
import {
    DdrMetricsFromJSON,
    DdrMetricsFromJSONTyped,
    DdrMetricsToJSON,
    DdrMetricsToJSONTyped,
} from './DdrMetrics';
import type { BpuMetrics } from './BpuMetrics';
import {
    BpuMetricsFromJSON,
    BpuMetricsFromJSONTyped,
    BpuMetricsToJSON,
    BpuMetricsToJSONTyped,
} from './BpuMetrics';
import type { IspMetrics } from './IspMetrics';
import {
    IspMetricsFromJSON,
    IspMetricsFromJSONTyped,
    IspMetricsToJSON,
    IspMetricsToJSONTyped,
} from './IspMetrics';
import type { SwapMetrics } from './SwapMetrics';
import {
    SwapMetricsFromJSON,
    SwapMetricsFromJSONTyped,
    SwapMetricsToJSON,
    SwapMetricsToJSONTyped,
} from './SwapMetrics';
import type { DiskMetrics } from './DiskMetrics';
import {
    DiskMetricsFromJSON,
    DiskMetricsFromJSONTyped,
    DiskMetricsToJSON,
    DiskMetricsToJSONTyped,
} from './DiskMetrics';
import type { GpuMetrics } from './GpuMetrics';
import {
    GpuMetricsFromJSON,
    GpuMetricsFromJSONTyped,
    GpuMetricsToJSON,
    GpuMetricsToJSONTyped,
} from './GpuMetrics';
import type { CpuMetrics } from './CpuMetrics';
import {
    CpuMetricsFromJSON,
    CpuMetricsFromJSONTyped,
    CpuMetricsToJSON,
    CpuMetricsToJSONTyped,
} from './CpuMetrics';
import type { NetMetrics } from './NetMetrics';
import {
    NetMetricsFromJSON,
    NetMetricsFromJSONTyped,
    NetMetricsToJSON,
    NetMetricsToJSONTyped,
} from './NetMetrics';
import type { VpuMetrics } from './VpuMetrics';
import {
    VpuMetricsFromJSON,
    VpuMetricsFromJSONTyped,
    VpuMetricsToJSON,
    VpuMetricsToJSONTyped,
} from './VpuMetrics';

/**
 * 
 * @export
 * @interface SystemMetrics
 */
export interface SystemMetrics {
    /**
     * 
     * @type {number}
     * @memberof SystemMetrics
     */
    ts: number;
    /**
     * 
     * @type {number}
     * @memberof SystemMetrics
     */
    uptimeS: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SystemMetrics
     */
    loadAvg: Array<number>;
    /**
     * 
     * @type {CpuMetrics}
     * @memberof SystemMetrics
     */
    cpu: CpuMetrics;
    /**
     * 
     * @type {MemoryMetrics}
     * @memberof SystemMetrics
     */
    memory: MemoryMetrics;
    /**
     * 
     * @type {SwapMetrics}
     * @memberof SystemMetrics
     */
    swap: SwapMetrics;
    /**
     * 
     * @type {DiskMetrics}
     * @memberof SystemMetrics
     */
    diskRoot: DiskMetrics;
    /**
     * 
     * @type {NetMetrics}
     * @memberof SystemMetrics
     */
    net: NetMetrics;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof SystemMetrics
     */
    tempsC: { [key: string]: number; };
    /**
     * 
     * @type {BpuMetrics}
     * @memberof SystemMetrics
     */
    bpu: BpuMetrics;
    /**
     * 
     * @type {VpuMetrics}
     * @memberof SystemMetrics
     */
    vpu: VpuMetrics;
    /**
     * 
     * @type {GpuMetrics}
     * @memberof SystemMetrics
     */
    gpu: GpuMetrics;
    /**
     * 
     * @type {DdrMetrics}
     * @memberof SystemMetrics
     */
    ddr: DdrMetrics;
    /**
     * 
     * @type {IspMetrics}
     * @memberof SystemMetrics
     */
    isp: IspMetrics;
    /**
     * 
     * @type {{ [key: string]: CoolingDevice; }}
     * @memberof SystemMetrics
     */
    cooling: { [key: string]: CoolingDevice; };
}

/**
 * Check if a given object implements the SystemMetrics interface.
 */
export function instanceOfSystemMetrics(value: object): value is SystemMetrics {
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('uptimeS' in value) || value['uptimeS'] === undefined) return false;
    if (!('loadAvg' in value) || value['loadAvg'] === undefined) return false;
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    if (!('swap' in value) || value['swap'] === undefined) return false;
    if (!('diskRoot' in value) || value['diskRoot'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    if (!('tempsC' in value) || value['tempsC'] === undefined) return false;
    if (!('bpu' in value) || value['bpu'] === undefined) return false;
    if (!('vpu' in value) || value['vpu'] === undefined) return false;
    if (!('gpu' in value) || value['gpu'] === undefined) return false;
    if (!('ddr' in value) || value['ddr'] === undefined) return false;
    if (!('isp' in value) || value['isp'] === undefined) return false;
    if (!('cooling' in value) || value['cooling'] === undefined) return false;
    return true;
}

export function SystemMetricsFromJSON(json: any): SystemMetrics {
    return SystemMetricsFromJSONTyped(json, false);
}

export function SystemMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'ts': json['ts'],
        'uptimeS': json['uptime_s'],
        'loadAvg': json['load_avg'],
        'cpu': CpuMetricsFromJSON(json['cpu']),
        'memory': MemoryMetricsFromJSON(json['memory']),
        'swap': SwapMetricsFromJSON(json['swap']),
        'diskRoot': DiskMetricsFromJSON(json['disk_root']),
        'net': NetMetricsFromJSON(json['net']),
        'tempsC': json['temps_c'],
        'bpu': BpuMetricsFromJSON(json['bpu']),
        'vpu': VpuMetricsFromJSON(json['vpu']),
        'gpu': GpuMetricsFromJSON(json['gpu']),
        'ddr': DdrMetricsFromJSON(json['ddr']),
        'isp': IspMetricsFromJSON(json['isp']),
        'cooling': (mapValues(json['cooling'], CoolingDeviceFromJSON)),
    };
}

export function SystemMetricsToJSON(json: any): SystemMetrics {
    return SystemMetricsToJSONTyped(json, false);
}

export function SystemMetricsToJSONTyped(value?: SystemMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ts': value['ts'],
        'uptime_s': value['uptimeS'],
        'load_avg': value['loadAvg'],
        'cpu': CpuMetricsToJSON(value['cpu']),
        'memory': MemoryMetricsToJSON(value['memory']),
        'swap': SwapMetricsToJSON(value['swap']),
        'disk_root': DiskMetricsToJSON(value['diskRoot']),
        'net': NetMetricsToJSON(value['net']),
        'temps_c': value['tempsC'],
        'bpu': BpuMetricsToJSON(value['bpu']),
        'vpu': VpuMetricsToJSON(value['vpu']),
        'gpu': GpuMetricsToJSON(value['gpu']),
        'ddr': DdrMetricsToJSON(value['ddr']),
        'isp': IspMetricsToJSON(value['isp']),
        'cooling': (mapValues(value['cooling'], CoolingDeviceToJSON)),
    };
}

