/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackerStatus
 */
export interface TrackerStatus {
    /**
     * 
     * @type {boolean}
     * @memberof TrackerStatus
     */
    tracking: boolean;
    /**
     * 
     * @type {string}
     * @memberof TrackerStatus
     */
    trackerType: string;
    /**
     * 
     * @type {number}
     * @memberof TrackerStatus
     */
    fps: number;
}

/**
 * Check if a given object implements the TrackerStatus interface.
 */
export function instanceOfTrackerStatus(value: object): value is TrackerStatus {
    if (!('tracking' in value) || value['tracking'] === undefined) return false;
    if (!('trackerType' in value) || value['trackerType'] === undefined) return false;
    if (!('fps' in value) || value['fps'] === undefined) return false;
    return true;
}

export function TrackerStatusFromJSON(json: any): TrackerStatus {
    return TrackerStatusFromJSONTyped(json, false);
}

export function TrackerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackerStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'tracking': json['tracking'],
        'trackerType': json['tracker_type'],
        'fps': json['fps'],
    };
}

export function TrackerStatusToJSON(json: any): TrackerStatus {
    return TrackerStatusToJSONTyped(json, false);
}

export function TrackerStatusToJSONTyped(value?: TrackerStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tracking': value['tracking'],
        'tracker_type': value['trackerType'],
        'fps': value['fps'],
    };
}

