/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoInfo
 */
export interface VideoInfo {
    /**
     * 
     * @type {number}
     * @memberof VideoInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof VideoInfo
     */
    sizeBytes: number;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    eventId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VideoInfo
     */
    hasLog?: boolean;
}

/**
 * Check if a given object implements the VideoInfo interface.
 */
export function instanceOfVideoInfo(value: object): value is VideoInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function VideoInfoFromJSON(json: any): VideoInfo {
    return VideoInfoFromJSONTyped(json, false);
}

export function VideoInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'filename': json['filename'],
        'url': json['url'],
        'sizeBytes': json['size_bytes'],
        'source': json['source'],
        'createdAt': json['created_at'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'hasLog': json['has_log'] == null ? undefined : json['has_log'],
    };
}

export function VideoInfoToJSON(json: any): VideoInfo {
    return VideoInfoToJSONTyped(json, false);
}

export function VideoInfoToJSONTyped(value?: VideoInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'filename': value['filename'],
        'url': value['url'],
        'size_bytes': value['sizeBytes'],
        'source': value['source'],
        'created_at': value['createdAt'],
        'event_id': value['eventId'],
        'has_log': value['hasLog'],
    };
}

