/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VpuMetrics
 */
export interface VpuMetrics {
    /**
     * 
     * @type {number}
     * @memberof VpuMetrics
     */
    clockMhz: number | null;
    /**
     * 
     * @type {number}
     * @memberof VpuMetrics
     */
    loadPercent: number | null;
}

/**
 * Check if a given object implements the VpuMetrics interface.
 */
export function instanceOfVpuMetrics(value: object): value is VpuMetrics {
    if (!('clockMhz' in value) || value['clockMhz'] === undefined) return false;
    if (!('loadPercent' in value) || value['loadPercent'] === undefined) return false;
    return true;
}

export function VpuMetricsFromJSON(json: any): VpuMetrics {
    return VpuMetricsFromJSONTyped(json, false);
}

export function VpuMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpuMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'clockMhz': json['clock_mhz'],
        'loadPercent': json['load_percent'],
    };
}

export function VpuMetricsToJSON(json: any): VpuMetrics {
    return VpuMetricsToJSONTyped(json, false);
}

export function VpuMetricsToJSONTyped(value?: VpuMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clock_mhz': value['clockMhz'],
        'load_percent': value['loadPercent'],
    };
}

