/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebRtcAnswerSchema
 */
export interface WebRtcAnswerSchema {
    /**
     * 
     * @type {string}
     * @memberof WebRtcAnswerSchema
     */
    sdp: string;
    /**
     * 
     * @type {string}
     * @memberof WebRtcAnswerSchema
     */
    type: string;
}

/**
 * Check if a given object implements the WebRtcAnswerSchema interface.
 */
export function instanceOfWebRtcAnswerSchema(value: object): value is WebRtcAnswerSchema {
    if (!('sdp' in value) || value['sdp'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WebRtcAnswerSchemaFromJSON(json: any): WebRtcAnswerSchema {
    return WebRtcAnswerSchemaFromJSONTyped(json, false);
}

export function WebRtcAnswerSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRtcAnswerSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'sdp': json['sdp'],
        'type': json['type'],
    };
}

export function WebRtcAnswerSchemaToJSON(json: any): WebRtcAnswerSchema {
    return WebRtcAnswerSchemaToJSONTyped(json, false);
}

export function WebRtcAnswerSchemaToJSONTyped(value?: WebRtcAnswerSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sdp': value['sdp'],
        'type': value['type'],
    };
}

