/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebRtcConfigSchema
 */
export interface WebRtcConfigSchema {
    /**
     * 
     * @type {number}
     * @memberof WebRtcConfigSchema
     */
    targetFps: number;
}

/**
 * Check if a given object implements the WebRtcConfigSchema interface.
 */
export function instanceOfWebRtcConfigSchema(value: object): value is WebRtcConfigSchema {
    if (!('targetFps' in value) || value['targetFps'] === undefined) return false;
    return true;
}

export function WebRtcConfigSchemaFromJSON(json: any): WebRtcConfigSchema {
    return WebRtcConfigSchemaFromJSONTyped(json, false);
}

export function WebRtcConfigSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRtcConfigSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'targetFps': json['target_fps'],
    };
}

export function WebRtcConfigSchemaToJSON(json: any): WebRtcConfigSchema {
    return WebRtcConfigSchemaToJSONTyped(json, false);
}

export function WebRtcConfigSchemaToJSONTyped(value?: WebRtcConfigSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_fps': value['targetFps'],
    };
}

