/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebRtcConfigSchemaPatch
 */
export interface WebRtcConfigSchemaPatch {
    /**
     * 
     * @type {number}
     * @memberof WebRtcConfigSchemaPatch
     */
    targetFps?: number | null;
}

/**
 * Check if a given object implements the WebRtcConfigSchemaPatch interface.
 */
export function instanceOfWebRtcConfigSchemaPatch(value: object): value is WebRtcConfigSchemaPatch {
    return true;
}

export function WebRtcConfigSchemaPatchFromJSON(json: any): WebRtcConfigSchemaPatch {
    return WebRtcConfigSchemaPatchFromJSONTyped(json, false);
}

export function WebRtcConfigSchemaPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRtcConfigSchemaPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'targetFps': json['target_fps'] == null ? undefined : json['target_fps'],
    };
}

export function WebRtcConfigSchemaPatchToJSON(json: any): WebRtcConfigSchemaPatch {
    return WebRtcConfigSchemaPatchToJSONTyped(json, false);
}

export function WebRtcConfigSchemaPatchToJSONTyped(value?: WebRtcConfigSchemaPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_fps': value['targetFps'],
    };
}

