# Generated by Django 5.2.11 on 2026-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_classes', models.JSONField(default=list)),
                ('servo_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aim Config',
            },
        ),
    ]
