# Generated by Django 5.2.11 on 2026-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aimconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='boxes', max_length=20)),
                ('conf_threshold', models.FloatField(default=0.4)),
                ('pixelcount_threshold', models.IntegerField(default=500)),
                ('min_area', models.IntegerField(default=500)),
                ('mog2_history', models.IntegerField(default=500)),
                ('mog2_var_threshold', models.IntegerField(default=16)),
                ('denoise_kernelsize', models.IntegerField(default=7)),
                ('mask_transparency', models.FloatField(default=0.5)),
            ],
            options={
                'verbose_name': 'Detection Config',
            },
        ),
    ]
