# Generated by Django 5.2.11 on 2026-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_type',
            field=models.CharField(default='CSRT', max_length=8),
        ),
    ]
