# Generated by Django 5.2.11 on 2026-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detectionconfig_tracker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_lost_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
