# Generated by Django 5.2.11 on 2026-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tracker_lost_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
