# Generated by Django 5.2.11 on 2026-04-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servo_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracker_lost_threshold',
        ),
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracker_type',
        ),
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracking_enabled',
        ),
    ]
