# Generated by Django 5.2.11 on 2026-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionconfig',
            name='mode',
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='show_boxes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='show_mask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='show_rois',
            field=models.BooleanField(default=False),
        ),
    ]
