# Generated by Django 5.2.11 on 2026-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_detectionconfig_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecordingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('pre_buffer_seconds', models.IntegerField(default=5)),
                ('post_trigger_seconds', models.IntegerField(default=10)),
                ('trigger_classes', models.JSONField(default=list)),
                ('cooldown_seconds', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Event Recording Config',
            },
        ),
    ]
