# Generated by Django 5.2.11 on 2026-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_eventrecordingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimconfig',
            name='vertical_angle_offset',
            field=models.FloatField(default=0.0),
        ),
    ]
