# Generated by Django 5.2.11 on 2026-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aimconfig_vertical_angle_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('trigger_classes', models.JSONField(default=list)),
                ('delay_seconds', models.FloatField(default=0.5)),
                ('duration_seconds', models.FloatField(default=1.0)),
                ('cooldown_seconds', models.FloatField(default=10.0)),
            ],
            options={
                'verbose_name': 'Splash Config',
            },
        ),
    ]
