# Generated by Django 5.2.11 on 2026-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_splashconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='show_seg',
            field=models.BooleanField(default=False),
        ),
    ]
