# Generated by Django 5.2.11 on 2026-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_detectionconfig_show_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimconfig',
            name='pan_invert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimconfig',
            name='tilt_invert',
            field=models.BooleanField(default=False),
        ),
    ]
