# Generated by Django 5.2.11 on 2026-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aimconfig_pan_invert_aimconfig_tilt_invert'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='bbox_ema_alpha',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='conf_threshold_keep',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='ghost_frames_ms',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='min_consecutive_frames',
            field=models.IntegerField(default=2),
        ),
    ]
