# Generated by Django 5.2.11 on 2026-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_detectionconfig_bbox_ema_alpha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zone', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
