# Generated by Django 5.2.11 on 2026-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_exclusionzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='event_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
