# Generated by Django 5.2.11 on 2026-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_video_event_id_video_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_confirm_hits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_iou_threshold',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_max_misses',
            field=models.IntegerField(default=10),
        ),
    ]
