# Generated by Django 5.2.11 on 2026-05-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_detectionconfig_tracker_confirm_hits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionconfig',
            name='show_seg',
        ),
    ]
