# Generated by Django 5.2.11 on 2026-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_detectionconfig_show_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimconfig',
            name='aim_confidence',
            field=models.FloatField(default=0.4),
        ),
    ]
