# Generated by Django 5.2.11 on 2026-05-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_aim_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splashconfig',
            name='trigger_classes',
        ),
    ]
