# Generated by Django 5.2.11 on 2026-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_splash_trigger_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashconfig',
            name='pump_duty',
            field=models.FloatField(default=100.0),
        ),
    ]
