# Generated by Django 5.2.11 on 2026-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_pump_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='servo_kalman_meas_noise',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='servo_kalman_process_noise',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='detectionconfig',
            name='bbox_ema_alpha',
            field=models.FloatField(default=0.7),
        ),
        migrations.RunSQL(
            # Update existing singleton to the new EMA default so the DB value
            # doesn't keep overriding the shared-memory default on startup.
            "UPDATE core_detectionconfig SET bbox_ema_alpha = 0.7 WHERE bbox_ema_alpha = 0.4;",
            reverse_sql="UPDATE core_detectionconfig SET bbox_ema_alpha = 0.4 WHERE bbox_ema_alpha = 0.7;",
        ),
    ]
