# Generated by Django 5.2.11 on 2026-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_kalman_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_reid_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_reid_hit_counter_max',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_reid_threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
