# Generated by Django 5.2.11 on 2026-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_drop_mjpeg_only_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracker_reid_enabled',
        ),
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracker_reid_hit_counter_max',
        ),
        migrations.RemoveField(
            model_name='detectionconfig',
            name='tracker_reid_threshold',
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_delta_t',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='tracker_inertia',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='detectionconfig',
            name='tracker_max_misses',
            field=models.IntegerField(default=30),
        ),
    ]
