# Generated by Django 5.2.11 on 2026-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_trackforge_ocsort'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='coord_ema_alpha',
            field=models.FloatField(default=1.0),
        ),
    ]
